import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <style jsx>  //component level scope write global in front of style jsx to make it global  
        {`
          .stylejsx {
            color: purple;
          }
        `}
      </style> */}
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my blog page</h1>
        <img
          className={styles.img}
          src="/home.jpg"
          width={400}
          height={266}
          alt="random image"
        />
        {/* div className={`${styles1.body} ${styles2.body}`} */}
        <p className={styles.description}>
          Get started by reading the one liked by the world 
        </p>
        {/* <p className="stylejsx">style jsx demo</p> */}
        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>
    </div>
  );
}
